studytracker/apps/studytracker/urls.py
from django.urls import path
from . import views
from apps.studytracker import views


app_name = 'studytracker'

urlpatterns = [
    path('<int:project_id>', views.project_detail, name='project_detail'),
    path('project/', views.project_new, name='project_new'),
    path('<int:project_id>/notes_list/', views.notes_list, name='notes_list'),
    path('<int:project_id>/notes_list/<int:note_id>/', views.note_detail, name='note_detail'),
    #ノート新規作成するページ
    path('<int:project_id>/note_list/create_note/', views.create_note, name='create_note'),
    #既存のノートを編集するページ
    path('<int:project_id>/note_list/<int:note_id>/edit_note/', views.edit_note, name='edit_note'),
    path('<int:project_id>/<int:task_id>/', views.task_detail, name='task_detail'),
    path('<int:project_id>/create_task/', views.create_task, name='create_task'),
    path('<int:project_id>/<int:task_id>/edit_task/',views.edit_task, name='edit_task'),
    path('settings/', views.settings, name='settings'),
    path('settings/change_password/', views.change_password, name='change_password'),
    path('settings/change_username/', views.change_username, name='change_username'),#ユーザーネーム変更
    path('settings/change_email/', views.change_email, name='change_email'),#メールアドレス変更

]

studytracker/config/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.studytracker import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentication/', include('apps.authentication.urls')),
    path('', views.top, name='top'),
    path('studytracker/', include('apps.studytracker.urls')),
]

studytracker/templates/setting/change_email.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/setting/change_email.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <title>APR_BASE</title>
</head>
<body>
    <header>
        <div class="logo"><a class="logo" href="{% url 'top' %}"><img src={% static "images/base/logo.png" %} alt="ロゴ"></a></div>

        <form method="get" action="#" class="search_container">
            <input type="text" size="25" placeholder="キーワード検索">
            <input type="submit" value="&#xf002">
        </form>
       
    </header>

    <div class="contents">
        <aside>
            <div class="row1">
                <button type="button" class="btn btn-outline-light"><a p class="back" href="{% url 'top' %}"><p>Projects</p></a></button>
            </div>
            <div class="row2">
                <button type="button" class="btn btn-outline-light"><a href="{% url 'logout' %}"><p>ログアウト</p></a></button>
                <button type="button" class="btn btn-outline-light"><a class="Setting" href="{% url 'studytracker:settings' %}"><p>Setting</p></a></button>
            </div>
        </aside>   

        <main>
            <div class="change-email">
                {% block content %}
                <div class="title">
                    <h2>メールアドレス変更</h2>
                </div>

                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit"><p>変更</p></button>
                </form>
                {% endblock %}
            </div>  
        </main>
    </div>
    
</body>
</html>

studytracker/templates/setting/change_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/setting/change_password.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <title>APR_BASE</title>
</head>
<body>
    <header>
        <div class="logo"><a class="logo" href="{% url 'top' %}"><img src={% static "images/base/logo.png" %} alt="ロゴ"></a></div>

        <form method="get" action="#" class="search_container">
            <input type="text" size="25" placeholder="キーワード検索">
            <input type="submit" value="&#xf002">
        </form>
       
    </header>

    <div class="contents">
        <aside>
            <div class="row1">
                <button type="button" class="btn btn-outline-light"><a p class="back" href="{% url 'top' %}"><p>Projects</p></a></button>
            </div>
            <div class="row2">
                <button type="button" class="btn btn-outline-light"><a href="{% url 'logout' %}"><p>ログアウト</p></a></button>
                <button type="button" class="btn btn-outline-light"><a class="Setting" href="{% url 'studytracker:settings' %}"><p>Setting</p></a></button>
            </div>
        </aside>   

        <main>
          <div class="change-password">
            {% block content %}
            <div class="title">
              <h2>パスワードの変更</h2>
            </div>

            <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit"><p>変更</p></button>
            </form>
            {% endblock %}
          </div>
        </main>
    </div>
    
</body>
</html>

studytracker/templates/setting/change_username.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/setting/change_username.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <title>APR_BASE</title>
</head>
<body>
    <header>
        <div class="logo"><a class="logo" href="{% url 'top' %}"><img src={% static "images/base/logo.png" %} alt="ロゴ"></a></div>

        <form method="get" action="#" class="search_container">
            <input type="text" size="25" placeholder="キーワード検索">
            <input type="submit" value="&#xf002">
        </form>
       
    </header>

    <div class="contents">
        <aside>
            <div class="row1">
                <button type="button" class="btn btn-outline-light"><a p class="back" href="{% url 'top' %}"><p>Projects</p></a></button>
            </div>
            <div class="row2">
                <button type="button" class="btn btn-outline-light"><a href="{% url 'logout' %}"><p>ログアウト</p></a></button>
                <button type="button" class="btn btn-outline-light"><a class="Setting" href="{% url 'studytracker:settings' %}"><p>Setting</p></a></button>
            </div>
        </aside>   

        <main>
            <div class="change-name">
                {% block content %}
                <div class="title">
                    <h2>ユーザーネーム変更</h2>
                </div>

                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit"><p>変更</p></button>
                </form>
                {% endblock %}
            </div>
        </main>
    </div>
    
</body>
</html>

studytracker/templates/setting/setting.html
 {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href={% static "css/setting/setting.css" %}>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <title>APR_BASE</title>
</head>
<body>
    <header>
        <div class="logo"><a class="logo" href="{% url 'top' %}"><img src={% static "images/base/logo.png" %} alt="ロゴ"></a></div>

        <form method="get" action="#" class="search_container">
            <input type="text" size="25" placeholder="キーワード検索">
            <input type="submit" value="&#xf002">
        </form>
       
    </header>

    <div class="contents">
        <aside>
            <div class="row1">
                <button type="button" class="btn btn-outline-light"><a p class="back" href="{% url 'top' %}"><p>Projects</p></a></button>
            </div>
            <div class="row2">
                <button type="button" class="btn btn-outline-light"><a href="{% url 'logout' %}"><p>ログアウト</p></a></button>
            </div>
        </aside>   

        <main>
            <h2>[設定]</h2>

            {% block content %}
            <div class="settings-container">
                <div class="project-list">
                    <div class="belong-project">
                        <h3>所属しているプロジェクト</h3>
                    </div>

                    <ul>
                        {% for project in projects %}
                        <li>
                            {{ project.project_name }}
                        </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="user">
                    <div class="imformation">
                        <h3>ユーザー情報</h3>
                    </div>

                    <div class="user-name">
                        <div>
                            <p>ユーザーネーム: {{ user.username }}</p>
                        </div>
                        <div>
                            <form method="post" action="{% url 'studytracker:change_username' %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary">Change Username</button>
                            </form>
                        </div>
                    </div>

                    <div class="user-email">
                        <div>
                            <p>メールアドレス: {{ user.email }}</p>
                        </div>
                        <div>
                            <form method="post" action="{% url 'studytracker:change_email' %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary">Change Email</button>
                            </form>
                        </div>
                    </div>

                    <div class="user-password">
                        <div>
                            <p>パスワード: **********</p>
                        </div>
                        <div>
                            <form method="post" action="{% url 'studytracker:change_password' %}">
                                {% csrf_token %}
                                {{ password_form.as_p }}
                                <button type="submit">Change Password</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {% endblock %}
        </main>
    </div>
    
</body>
</html>