studytracker/apps/studytracker/urls.py
from django.urls import path
from . import views
from apps.studytracker import views


app_name = 'studytracker'

urlpatterns = [
    path('<int:project_id>', views.project_detail, name='project_detail'),
    path('project/', views.project_new, name='project_new'),
    path('<int:project_id>/notes_list/', views.notes_list, name='notes_list'),
    path('<int:project_id>/notes_list/<int:note_id>/', views.note_detail, name='note_detail'),
    #ノート新規作成するページ
    path('<int:project_id>/note_list/create_note/', views.create_note, name='create_note'),
    #既存のノートを編集するページ
    path('<int:project_id>/note_list/<int:note_id>/edit_note/', views.edit_note, name='edit_note'),
    path('<int:project_id>/<int:task_id>/', views.task_detail, name='task_detail'),
    path('<int:project_id>/create_task/', views.create_task, name='create_task'),
    path('<int:project_id>/<int:task_id>/edit_task/',views.edit_task, name='edit_task'),
    path('settings/', views.settings, name='settings'),
    path('settings/change_password/', views.change_password, name='change_password'),
    path('settings/change_username/', views.change_username, name='change_username'),#ユーザーネーム変更
    path('settings/change_email/', views.change_email, name='change_email'),#メールアドレス変更

]

studytracker/config/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.studytracker import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentication/', include('apps.authentication.urls')),
    path('', views.top, name='top'),
    path('studytracker/', include('apps.studytracker.urls')),
]

studytracker/templates/task/create_task.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href={% static "css/top/base_style.css" %}>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>APR_BASE</title>
</head>
<body>
    <header>
        <div class="logo"><a class="logo" href="{% url 'top' %}"><img src={% static "images/base/logo.png" %} alt="ロゴ"></a></div>

        <form method="get" action="#" class="search_container">
            <input type="text" size="25" placeholder="キーワード検索">
            <input type="submit" value="&#xf002">
        </form>
       
    </header>

    <div class="contents">
        <aside>
            <div class="row1">
                <button type="button" class="btn btn-outline-light"><a p class="back" href="{% url 'top' %}"><p>Projects</p></a></button>
                <button type="button" class="btn btn-outline-light"><a class="task" href="{% url 'studytracker:project_detail' project.project_id %}"><p>Task</p></a></button>
                <button type="button" class="btn btn-outline-light"><a class="note" href="{% url 'studytracker:notes_list' project_id=project.project_id %}"><p>Notes</p></a></button>
                <button type="button" class="btn btn-outline-light"><a class="Setting" href="{% url 'studytracker:settings' %}"><p>Setting</p></a></button>
            </div>
            <div class="row2">
                <button type="button" class="btn btn-outline-light"><a href="{% url 'logout' %}"><p>ログアウト</p></a></button>
            </div>
        </aside>

        <main>
            <div class="card">
                <div class="card-body">
                    <h1>Create Task</h1>
                    <form method="POST" class="mx-3 mx-md-5">{% csrf_token %}
                        {% bootstrap_form form %} 
                        {% bootstrap_button button_type="submit" content="Create" size="lg" %}
                    </form>
                </div>
            </div>
        </main>
    </div>    
</body>
</html>

studytracker/templates/task/detail_task.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href={% static "css/top/base_style.css" %}>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <title>APR_BASE</title>
</head>
<body>
    <header>
        <div class="logo"><a class="logo" href="{% url 'top' %}"><img src={% static "images/base/logo.png" %} alt="ロゴ"></a></div>

        <form method="get" action="#" class="search_container">
            <input type="text" size="25" placeholder="キーワード検索">
            <input type="submit" value="&#xf002">
        </form>
       
    </header>

    <div class="contents">
        <aside>
            <div class="row1">
                <button type="button" class="btn btn-outline-light"><a p class="back" href="{% url 'top' %}"><p>Projects</p></a></button>
                <button type="button" class="btn btn-outline-light"><a class="task" href="{% url 'studytracker:project_detail' project.project_id %}"><p>Task</p></a></button>
                <button type="button" class="btn btn-outline-light"><a class="note" href="{% url 'studytracker:notes_list' project_id=project.project_id %}"><p>Notes</p></a></button>
                <button type="button" class="btn btn-outline-light"><a class="Setting" href="{% url 'studytracker:settings' %}"><p>Setting</p></a></button>
            </div>
            <div class="row2">
                <button type="button" class="btn btn-outline-light"><a href="{% url 'logout' %}"><p>ログアウト</p></a></button>
            </div>
        </aside>

        <main>
            <h1>{{ task.task_name }}'s Detail</h1>
            <p>Description:{{ task.description }}</p>
            <p>Deadline:{{ task.deadline }}</p>
            <a href="{% url 'studytracker:edit_task' project_id=project.project_id task_id=task.task_id %}" class="project-title">編集</a>
            <form method="post">
                {% csrf_token %}
                <button type="submit" name="delete_task">削除</button>
            </form>
            <a href="{% url 'studytracker:project_detail' project.project_id %}" class="project-title">Back to Task List</a>
        </main>
    </div>
</body>
</html>

studytracker/templates/task/edit_task.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href={% static "css/top/base_style.css" %}>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>APR_BASE</title>
</head>
<body>
    <header>
        <div class="logo"><a class="logo" href="{% url 'top' %}"><img src={% static "images/base/logo.png" %} alt="ロゴ"></a></div>

        <form method="get" action="#" class="search_container">
            <input type="text" size="25" placeholder="キーワード検索">
            <input type="submit" value="&#xf002">
        </form>
       
    </header>

    <div class="contents">
        <aside>
            <div class="row1">
                    <button type="button" class="btn btn-outline-light"><a p class="back" href="{% url 'top' %}"><p>Projects</p></a></button>
                    <button type="button" class="btn btn-outline-light"><a class="task" href="{% url 'studytracker:project_detail' project_id=project.project_id %}"><p>Task</p></a></button>
                    <button type="button" class="btn btn-outline-light"><a class="note" href="{% url 'studytracker:notes_list' project_id=project.project_id %}"><p>Notes</p></a></button>
                    <button type="button" class="btn btn-outline-light"><a class="Setting" href="{% url 'studytracker:settings' %}"><p>Setting</p></a></button>
            </div>
            <div class="row2">
                <button type="button" class="btn btn-outline-light"><a href="{% url 'logout' %}"><p>ログアウト</p></a></button>
            </div>
        </aside>

        <main>
            <div class="card">
                <div class="card-body">
                    <h1>Edit Task</h1>
                    <form method="POST" class="mx-3 mx-md-5">{% csrf_token %}
                        {% bootstrap_form form %} 
                        {% bootstrap_button button_type="submit" content="Create" size="lg" %}
                    </form>
                </div>
            </div>
        </main>
    </div>
</body>
</html>